# Generated by Django 5.2.8 on 2025-12-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file_url',
            field=models.URLField(),
        ),
    ]
