# Generated by Django 5.2.8 on 2025-11-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_assigned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
