# Generated by Django 5.2.8 on 2025-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fully_booked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
