# Generated by Django 5.2.8 on 2026-09-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_benchmark_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas_of_expertise',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='project_interests',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
