# Generated by Django 5.2.8 on 2026-01-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_guest',
        ),
    ]
