# Generated by Django 5.2.8 on 2025-12-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('proposal', 'Proposal'), ('chapter_one', 'Chapter One'), ('chapter_two', 'Chapter Two'), ('final_report', 'Final Report')], max_length=50)),
                ('file_url', models.FileField(upload_to='submissions/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project')),
            ],
        ),
    ]
