# Generated by Django 5.2.8 on 2025-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_submission_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
