# Generated by Django 5.2.8 on 2026-01-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('proposal_pending', 'Proposal Pending'), ('proposal_approved', 'Proposal Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='proposal_pending', max_length=50),
        ),
    ]
