# Generated by Django 5.2.8 on 2026-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
