# Generated by Django 5.2.8 on 2026-08-30 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tag_user_capacity_user_expertise_tags'),
        ('projects', '0007_submission_is_rejected_submission_rejection_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectsession'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='accounts.tag'),
        ),
        migrations.AddField(
            model_name='projectsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='extraction_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('empty', 'Empty'), ('too_large', 'Too Large'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='previous',
            field=models.ForeignKey(blank=True, help_text='The immediately preceding version of this project/milestone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='projects.submission'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('project', 'milestone', 'version')},
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('feedback', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission'], name='projects_su_submiss_9253f1_idx'), models.Index(fields=['reviewer'], name='projects_su_reviewe_cab4f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupervisorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('meeting', 'Meeting'), ('message', 'Message'), ('email', 'Email'), ('other', 'Other')], default='message', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['supervisor', 'session'], name='projects_su_supervi_062956_idx'), models.Index(fields=['student'], name='projects_su_student_7bfe0b_idx')],
            },
        ),
    ]
